# gitlab-runner-config.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
data:
  config.toml: |-
    concurrent = 4
    [[runners]]
      name = "Kubernetes Demo Default NS"
      url = "http://gitlabdemovm1.easfcgieyxie5j20kopcgnp4gd.bx.internal.cloudapp.net"
      token = "glrt-6EZv8vdFiQUdnvW8cF33"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "default"
        poll_timeout = 600
        cpu_request = "1"
        service_cpu_request = "200m"
