build-job-1: 
  stage: build 
  script: 
    - cat /etc/os-release 

build-job-2: 
  stage: build 
  script: 
    - date

compile: 
  stage: compile
  needs: ["build-job-1", "build-job-2"]
  variables:
    COMPILE_JOB_VAR: "This is a Compile JOB Var"  
  script: 
    - cat helloworld.txt myprojectfile.txt README.md > complied.txt  
    - echo "Variables are '$GLOBAL_VAR', '$COMPILE_JOB_VAR', '$CI_COMMIT_BRANCH', '$PIPELINE_NAME'"
  artifacts:
    paths:
      - complied.txt   
    expire_in: 20 minutes

cache:
  key: "$CI_BUILD_REF"
  paths:
    - complied.txt     